import SearchHeader from "@/components/SearchHeader";
import Head from "next/head";
import React from "react";
import SearchOptions from "@/components/SearchOptions";

const search = () => {
  return (
    <div className="flex flex-col">
      <Head>
        <title>Search page</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <SearchHeader />
      <SearchOptions />
    </div>
  );
};

export default search;
